stages:
  - test
  - deploy

Gradle Test:
  image: java:8
  stage: test
  script:
  - ./gradlew test

Deployment:
  image: ruby:2.4
  stage: deploy
  only:
    - master
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
    - export HEROKU_API_KEY=$HEROKU_APIKEY
  environment:
    name: production
    url: $HEROKU_APP_HOST
